server:
  port: 8688
  servlet:
    context-path: /tuimm/v1

spring:
  application:
    name: backend-technical-test
  datasource:
    driverClassName: org.h2.Driver
    url: "jdbc:h2:mem:testdb"
    password: "sa"
    username: "password"
    testOnBorrow: true
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: SELECT 1
    max-active: 15
    max-idle: 10
    max-wait: 8000
  kafka:
    consumer:
      auto-offset-reset: earliest
      group-id: group-1
    topic: cooking
    bootstrap-servers: localhost:29092
flyway:
  url: jdbc:h2:mem:testdb
  schemas: USERSERVICE
  user: "sa"
  password: "password"
  locations: classpath:db/migration

order:
  updateTime: 300 # time in seconds

com.scheduling:
  cron: "0/30 * * * * *" # Every 30 seconds
  enabled: true