CREATE TABLE ADDRESS
(
    ID        INT AUTO_INCREMENT PRIMARY KEY,
    STREET    VARCHAR(80) NOT NULL,
    POST_CODE VARCHAR(80) NOT NULL,
    CITY      VARCHAR(80) NOT NULL,
    COUNTRY   VARCHAR(80) NOT NULL
);

INSERT INTO ADDRESS (STREET, POST_CODE, CITY, COUNTRY)
VALUES ('C/JOAN MESTRE, 20',
        '07005', 'PALMA', 'SPAIN');
INSERT INTO ADDRESS (STREET, POST_CODE, CITY, COUNTRY)
VALUES ('C/DIAZ HUERTAS, 1',
        '14012', 'CORDOBA', 'SPAIN');


CREATE TABLE CLIENT
(
    ID         INT AUTO_INCREMENT PRIMARY KEY,
    FIRST_NAME VARCHAR(80) NOT NULL,
    LAST_NAME  VARCHAR(80) NOT NULL,
    TELEPHONE  VARCHAR(80) NOT NULL,
    CONSTRAINT CLIENT_UK UNIQUE (TELEPHONE)
);

INSERT INTO CLIENT (FIRST_NAME, LAST_NAME, TELEPHONE)
VALUES ('LUCA',
        'SALETTA', '600097595');
INSERT INTO CLIENT (FIRST_NAME, LAST_NAME, TELEPHONE)
VALUES ('PAOLO',
        'SALETTA', '625082506');
INSERT INTO CLIENT (FIRST_NAME, LAST_NAME, TELEPHONE)
VALUES ('PAOLA',
        'SALETTA', '625082515');
INSERT INTO CLIENT (FIRST_NAME, LAST_NAME, TELEPHONE)
VALUES ('MARIA',
        'SILLERO', '646462960');


CREATE TABLE ORDERS
(
    ID            INT AUTO_INCREMENT PRIMARY KEY,
    CLIENT_ID     INT       NOT NULL,
    ADDRESS_ID    INT       NOT NULL,
    CREATION_DATE TIMESTAMP NOT NULL,
    PILOTES       INT       NOT NULL,
    ORDER_TOTAL   INT       NOT NULL,
    DONE          INT       NOT NULL,
    CONSTRAINT ADDRESS_FK FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS (ID),
    CONSTRAINT CLIENT_FK FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT (ID)
);

INSERT INTO ORDERS (CLIENT_ID, ADDRESS_ID, CREATION_DATE, PILOTES, ORDER_TOTAL, DONE)
VALUES (1, 1,
        to_timestamp('14/06/20 00:00:00,000000000', 'DD/MM/RR HH24:MI:SSXFF'), 5, 1, 1);

INSERT INTO ORDERS (CLIENT_ID, ADDRESS_ID, CREATION_DATE, PILOTES, ORDER_TOTAL, DONE)
VALUES (1, 1,
        to_timestamp('14/05/20 00:00:00,000000000', 'DD/MM/RR HH24:MI:SSXFF'), 10, 2, 1);

INSERT INTO ORDERS (CLIENT_ID, ADDRESS_ID, CREATION_DATE, PILOTES, ORDER_TOTAL, DONE)
VALUES (2, 2,
        to_timestamp('14/05/20 00:00:00,000000000', 'DD/MM/RR HH24:MI:SSXFF'), 10, 2, 1);

INSERT INTO ORDERS (CLIENT_ID, ADDRESS_ID, CREATION_DATE, PILOTES, ORDER_TOTAL, DONE)
VALUES (3, 2,
        to_timestamp('14/05/20 00:00:00,000000000', 'DD/MM/RR HH24:MI:SSXFF'), 15, 3, 1);

INSERT INTO ORDERS (CLIENT_ID, ADDRESS_ID, CREATION_DATE, PILOTES, ORDER_TOTAL, DONE)
VALUES (4, 2,
        to_timestamp('14/05/20 00:00:00,000000000', 'DD/MM/RR HH24:MI:SSXFF'), 10, 2, 1);
