CREATE SEQUENCE ADDRESS_SEQ MINVALUE 1 MAXVALUE 999999999 START WITH 1 INCREMENT BY 1;


CREATE TABLE ADDRESS
(
    ID        INT DEFAULT ADDRESS_SEQ.NEXTVAL PRIMARY KEY,
    STREET    VARCHAR(80) NOT NULL,
    POST_CODE VARCHAR(80) NOT NULL,
    CITY      VARCHAR(80) NOT NULL,
    COUNTRY   VARCHAR(80) NOT NULL
);

INSERT INTO ADDRESS (STREET, POST_CODE, CITY, COUNTRY)
VALUES ('C/JOAN MESTRE, 20',
        '07005', 'PALMA', 'SPAIN');

INSERT INTO ADDRESS (STREET, POST_CODE, CITY, COUNTRY)
VALUES ('C/DIAZ HUERTAS, 1',
        '14012', 'CORDOBA', 'SPAIN');

INSERT INTO ADDRESS (STREET, POST_CODE, CITY, COUNTRY)
VALUES ('C/NOGAL, 1',
        '14011', 'CORDOBA', 'SPAIN');

INSERT INTO ADDRESS (STREET, POST_CODE, CITY, COUNTRY)
VALUES ('C/GENERAL RIERA, 1',
        '07005', 'PALMA', 'SPAIN');


CREATE SEQUENCE CLIENT_SEQ MINVALUE 1 MAXVALUE 999999999 START WITH 1 INCREMENT BY 1;

CREATE TABLE CLIENT
(
    ID         INT DEFAULT CLIENT_SEQ.NEXTVAL PRIMARY KEY,
    FIRST_NAME VARCHAR(80) NOT NULL,
    LAST_NAME  VARCHAR(80) NOT NULL,
    TELEPHONE  VARCHAR(80) NOT NULL,
    CONSTRAINT CLIENT_UK UNIQUE (TELEPHONE)
);

INSERT INTO CLIENT (FIRST_NAME, LAST_NAME, TELEPHONE)
VALUES ('LUCA',
        'SALETTA', '600097595');
INSERT INTO CLIENT (FIRST_NAME, LAST_NAME, TELEPHONE)
VALUES ('PAOLO',
        'SALETTA', '625082506');
INSERT INTO CLIENT (FIRST_NAME, LAST_NAME, TELEPHONE)
VALUES ('PAOLA',
        'SALETTA', '625082515');
INSERT INTO CLIENT (FIRST_NAME, LAST_NAME, TELEPHONE)
VALUES ('MARIA',
        'SILLERO', '646462960');


CREATE SEQUENCE ORDER_SEQ MINVALUE 1 MAXVALUE 999999999 START WITH 1 INCREMENT BY 1;

CREATE TABLE ORDERS
(
    ID            INT DEFAULT ORDER_SEQ.NEXTVAL PRIMARY KEY,
    CLIENT_ID     INT         NOT NULL,
    ADDRESS_ID    INT         NOT NULL,
    CREATION_DATE TIMESTAMP   NOT NULL,
    PILOTES       INT         NOT NULL,
    ORDER_TOTAL   FLOAT,
    STATUS        VARCHAR(15) NOT NULL,
    CONSTRAINT ADDRESS_FK FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS (ID),
    CONSTRAINT CLIENT_FK FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT (ID)
);

INSERT INTO ORDERS (CLIENT_ID, ADDRESS_ID, CREATION_DATE, PILOTES, ORDER_TOTAL, STATUS)
VALUES (1, 1,
        to_timestamp('14/06/20 00:00:00,000000000', 'DD/MM/RR HH24:MI:SSXFF'), 5, 1, 'DONE');

INSERT INTO ORDERS (CLIENT_ID, ADDRESS_ID, CREATION_DATE, PILOTES, ORDER_TOTAL, STATUS)
VALUES (1, 1,
        to_timestamp('14/05/20 00:00:00,000000000', 'DD/MM/RR HH24:MI:SSXFF'), 10, 2, 'DONE');

INSERT INTO ORDERS (CLIENT_ID, ADDRESS_ID, CREATION_DATE, PILOTES, ORDER_TOTAL, STATUS)
VALUES (2, 2,
        to_timestamp('14/05/20 00:00:00,000000000', 'DD/MM/RR HH24:MI:SSXFF'), 10, 2, 'DONE');

INSERT INTO ORDERS (CLIENT_ID, ADDRESS_ID, CREATION_DATE, PILOTES, ORDER_TOTAL, STATUS)
VALUES (3, 3,
        to_timestamp('14/05/20 00:00:00,000000000', 'DD/MM/RR HH24:MI:SSXFF'), 15, 3, 'DONE');

INSERT INTO ORDERS (CLIENT_ID, ADDRESS_ID, CREATION_DATE, PILOTES, ORDER_TOTAL, STATUS)
VALUES (4, 4,
        to_timestamp('14/05/20 00:00:00,000000000', 'DD/MM/RR HH24:MI:SSXFF'), 10, 2, 'DONE');

-- PENDING ORDERS
INSERT INTO ORDERS (CLIENT_ID, ADDRESS_ID, CREATION_DATE, PILOTES, ORDER_TOTAL, STATUS)
VALUES (4, 4,
        to_timestamp('14/05/20 00:00:00,000000000', 'DD/MM/RR HH24:MI:SSXFF'), 10, 2, 'PENDING');

INSERT INTO ORDERS (CLIENT_ID, ADDRESS_ID, CREATION_DATE, PILOTES, ORDER_TOTAL, STATUS)
VALUES (4, 4,
        to_timestamp('14/05/20 00:00:00,000000000', 'DD/MM/RR HH24:MI:SSXFF'), 10, 2, 'PENDING');

INSERT INTO ORDERS (CLIENT_ID, ADDRESS_ID, CREATION_DATE, PILOTES, ORDER_TOTAL, STATUS)
VALUES (4, 4,
        to_timestamp('14/05/22 00:00:00,000000000', 'DD/MM/RR HH24:MI:SSXFF'), 10, 2, 'PENDING');
